### ISSUE TITLE
Failed to activate the coffee-autocompile package

### ISSUE THREAD

**Issue by sudofx** [olmokramer/atom-coffee-autocompile#3]
[Enter steps to reproduce below:]

1. Save .coffee script 

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [coffee-autocompile](https://github.com/olmokramer/atom-coffee-autocompile) package, v0.3.1

### Stack Trace

Failed to activate the coffee-autocompile package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

  at Function (native)
  at Object.<anonymous> (/Users/rjohnson/.atom/packages/coffee-autocompile/node_modules/uglify-js/tools/node.js:24:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/rjohnson/.atom/packages/coffee-autocompile/lib/coffee-autocompile.js:30:17)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:241:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:17.3.0 git-projects:toggle (atom-pane.pane.active)
     -0:15.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".svn",
      ".DS_Store",
      "*.pyc",
      "__pycache__",
      "Thumbs.db",
      ".localized",
      "$RECYCLE.BIN"
    ],
    "projectHome": "~/Developer",
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
coffee-autocompile, v0.3.1
git-log, v0.4.1
git-projects, v1.15.0
language-nginx, v0.6.1
language-swift, v0.4.0
minimap, v4.13.4
move-status-items, v0.0.11
remote-atom, v1.2.7
set-syntax, v0.3.0
sync-settings, v0.6.0
term3, v0.19.0
tool-bar, v0.1.9
tool-bar-almighty, v0.1.3
untitled-no-more, v0.1.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by olmokramer** [comment]
Thanks for the report. Looking into this

**Comment by olmokramer** [comment]
I just published a new version that should fix this. Please let me know if it works

**Comment by olmokramer** [comment]
Oops, I forgot to include a dependency in package.json. v0.3.5 should fix this.
